### PR TITLE
Activity tracker

### PR DESCRIPTION
**Pull request by rachaelrobinson**
Activity tracker now in it's own file (for the bean)

### CODE REVIEW

**Comment by arthurberman** [comment]
Would you please add some comments to the code so it's more clear what information is being used/tracked?

**Comment by arthurberman** [comment]
This looks great. I'd like one more thing, which is something I still need to do as well. Would you please leave a comment at the top of each .ino file specifying which device the file runs on? I will do the same for my commit. This way, the individual components will be clearly labelled.

**Comment by rachaelrobinson** [comment]
Oh great idea! Will do right now

**Comment by arthurberman** [comment]
Looks good! Feel free to merge and close.

**Pull request merged**
